name: MCMG
version: 1.0.0
author: Than00ber
main: com.than00ber.mcmg.Main
api-version: 1.17

softdepend: [ProtocolLib, LibsDisguises]

commands:
  minigame:
    description: Allows to start, end and restart games
    usage: /minigame [start | end | restart | play] <Option?>
    permission: admin
  configs:
    description: Allows editing of all current minigame properties
    usage: /configs <Property> <Option?>
    permission: admin
  vote:
    description: Admins can initiate a vote for the current game
    usage: /vote
    permission: admin
  ready:
    description: Players can vote when they are ready to start a new minigame
    usage: /ready
    permission: none
  assign:
    description: Assigns a player to a minigame team
    usage: /assign <Name> <Team>
    permission: admin

permissions:
  none:
    default: true
    description: Lowest permission level, gives no access to commands
  admin:
    default: op
    description: Highest permission level, gives access to all commands
