name: MCMG
version: 1.0.0
author: Than00ber
main: com.than00ber.mcmg.Main
api-version: 1.18

depend: [ProtocolLib]

commands:
  game:
    description: Allows to start, end and restart games
    usage: /game [start | end | restart | play] <Option?>
    permission: admin
  configs:
    description: Allows editing of all current game properties
    usage: /configs <Property> <Option?>
    permission: admin
  ready:
    description: Players can vote when they are ready to start a new game
    usage: /ready
    permission: none
  fakeplayer:
    description: Adds a fake player for dev testing
    usage: /fakeplayer <Name?>
    permission: admin

permissions:
  none:
    default: true
    description: Lowest permission level, gives no access to commands
  admin:
    default: op
    description: Highest permission level, gives access to all commands
