name: MCMG
version: 1.0.0
author: Than00ber
main: com.than00ber.mcmg.Main
api-version: 1.18

commands:
  game:
    description: Allows to start, end and restart games
    usage: /game [start | end | restart | play] <Option?>
    permission: admin

permissions:
  none:
    default: true
    description: Lowest permission level, gives no access to commands
  admin:
    default: op
    description: Highest permission level, gives access to all commands